/* this code was automatically generated by wwwc */
#include "synth_source.h"
error_code getMainWave(Wave **out) {
Wave *mainWave = (Wave *) malloc(sizeof(Wave));
if (!mainWave) { *out = NULL; return ALLOCATION_FAIL; }
combined_wave *combiner0 = calloc(1, sizeof(combined_wave));
mainWave->base.isValue = 3;
mainWave->base.content.combined = combiner0;
combiner0->combiner = add_waves;
combined_wave *combiner1 = calloc(1, sizeof(combined_wave));
combiner0->value1.isValue = 3;
combiner0->value1.content.combined = combiner1;
combiner1->combiner = add_waves;
combiner1->value2.isValue = 1;
combiner1->value2.content.value = 1;
combiner0->value1.isValue = 1;
combiner0->value1.content.value = 2;
combiner0->value2.isValue = 1;
combiner0->value2.content.value = 3;
combined_wave *combiner2 = calloc(1, sizeof(combined_wave));
mainWave->frequency.isValue = 3;
mainWave->frequency.content.combined = combiner2;
combiner2->combiner = add_waves;
combiner2->value1.isValue = 1;
combiner2->value1.content.value = 1;
combined_wave *combiner3 = calloc(1, sizeof(combined_wave));
combiner2->value2.isValue = 3;
combiner2->value2.content.combined = combiner3;
combiner3->combiner = add_waves;
combiner3->value2.isValue = 1;
combiner3->value2.content.value = 2;
combiner2->value2.isValue = 1;
combiner2->value2.content.value = 3;
/* default values */
mainWave->offset.isValue = 1;
mainWave->offset.content.value = 0;
mainWave->amplitude.isValue = 1;
mainWave->amplitude.content.value = 1;
mainWave->phase.isValue = 1;
mainWave->phase.content.value = 0;
mainWave->attack.isValue = 1;
mainWave->attack.content.value = 0;
mainWave->decay.isValue = 1;
mainWave->decay.content.value = 0;
mainWave->sustain.isValue = 1;
mainWave->sustain.content.value = 1;
mainWave->release.isValue = 1;
mainWave->release.content.value = 0;
mainWave->cutoff.isValue = 1;
mainWave->cutoff.content.value = 0;
mainWave->resonance.isValue = 1;
mainWave->resonance.content.value = 0;
*out = mainWave;
return OK;
}