/* this code was automatically generated by wwwc */
#include "synth_source.h"
error_code getMainWave(Wave **out) {
Wave *mainWave = (Wave *) malloc(sizeof(Wave));
if (!mainWave) { *out = NULL; return ALLOCATION_FAIL; }
mainWave->shape = SINE;
mainWave->base.isValue = 1;
mainWave->base.content.value = 0;
mainWave->amplitude.isValue = 2;
mainWave->amplitude.content.midi_value = VELOCITY;
mainWave->frequency.isValue = 2;
mainWave->frequency.content.midi_value = FREQUENCY;
mainWave->phase.isValue = 1;
mainWave->phase.content.value = 0;
mainWave->attack.isValue = 1;
mainWave->attack.content.value = 0.100000;
mainWave->decay.isValue = 1;
mainWave->decay.content.value = 2;
mainWave->sustain.isValue = 1;
mainWave->sustain.content.value = 0;
mainWave->release.isValue = 1;
mainWave->release.content.value = 0;
/* default values */
mainWave->cutoff.isValue = 1;
mainWave->cutoff.content.value = 0;
mainWave->resonance.isValue = 1;
mainWave->resonance.content.value = 0;
*out = mainWave;
return OK;
}